FROM neurips2022nmmo/evaluator:latest

WORKDIR /home/aicrowd

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY maps maps

COPY keepers keepers

COPY evaluator.py evaluator.py
COPY pvp pvp
COPY pkg pkg

CMD ["bash"]

